# Generated by Django 5.0.6 on 2024-05-10 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingdetail',
            name='candidate_references',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='openingdetail',
            name='corporate_references',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='openingdetail',
            name='financial',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='openingdetail',
            name='miscellaneous',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openingdetail',
            name='miscellaneous_choice',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='openingdetail',
            name='potential_resources',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='openingdetail',
            name='security',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='openingdetail',
            name='technical_evaluation_for_resume',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='openingdetail',
            name='education',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted')], default='N/A', max_length=20),
        ),
    ]
