# Generated by Django 5.0.6 on 2024-05-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openingapp', '0002_projectinformation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='openings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_info', to='openingapp.opening'),
        ),
    ]
