# Generated by Django 5.0.6 on 2024-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openingapp', '0003_projectinformation_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='project_title',
            field=models.CharField(default='anything', max_length=75),
            preserve_default=False,
        ),
    ]
