# Generated by Django 5.0.4 on 2024-04-30 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('sol_no', models.CharField(blank=True, max_length=255, null=True)),
                ('task_auth_no', models.CharField(blank=True, max_length=255, null=True)),
                ('t_auth_name', models.CharField(blank=True, max_length=255, null=True)),
                ('t_auth_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('t_auth_fax_no', models.CharField(blank=True, max_length=15, null=True)),
                ('t_auth_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('t_auth_address', models.CharField(blank=True, max_length=255, null=True)),
                ('p_auth_name', models.CharField(blank=True, max_length=255, null=True)),
                ('p_auth_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('p_auth_fax_no', models.CharField(blank=True, max_length=15, null=True)),
                ('p_auth_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('p_auth_address', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refapp.applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refapp.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BiderSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('activity_deliverable', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refapp.company')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refapp.organization')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refapp.resource')),
            ],
        ),
    ]
