# Generated by Django 5.0.4 on 2024-04-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'reference', 'verbose_name_plural': 'references'},
        ),
        migrations.AlterField(
            model_name='bidersupplier',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='refapp.organization'),
        ),
        migrations.AlterField(
            model_name='bidersupplier',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='refapp.organization'),
        ),
        migrations.AlterModelTable(
            name='reference',
            table='reference',
        ),
    ]
