# Generated by Django 5.0.4 on 2024-05-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refapp', '0003_rename_p_auth_address_reference_project_auth_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterModelOptions(
            name='activitydeliverable',
            options={'verbose_name': 'activitydeliverable', 'verbose_name_plural': 'activityderliverables'},
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'applicant', 'verbose_name_plural': 'applicants'},
        ),
        migrations.AlterModelOptions(
            name='biddersupplier',
            options={'verbose_name': 'biddersupplier', 'verbose_name_plural': 'biddersuppliers'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
        migrations.AlterField(
            model_name='activitydeliverable',
            name='activity_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='refapp.biddersupplier'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='refapp.biddersupplier'),
        ),
        migrations.AlterModelTable(
            name='activitydeliverable',
            table='activitydeliverable',
        ),
        migrations.AlterModelTable(
            name='applicant',
            table='applicant',
        ),
        migrations.AlterModelTable(
            name='biddersupplier',
            table='biddersupplier',
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='resource',
        ),
    ]
