# Generated by Django 5.0.6 on 2024-05-16 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_openings', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'opening',
                'verbose_name_plural': 'openings',
                'db_table': 'opening',
            },
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_resume', models.FileField(blank=True, null=True, upload_to='')),
                ('exclusivity_agreement', models.FileField(blank=True, null=True, upload_to='')),
                ('nda', models.FileField(blank=True, null=True, upload_to='')),
                ('education', models.FileField(blank=True, null=True, upload_to='')),
                ('candidate_reference', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'project_files',
                'verbose_name_plural': 'project_files',
                'db_table': 'project_files',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfoUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
                ('hourly_bill_rate', models.CharField(max_length=255)),
                ('hourly_pay_rate', models.CharField(max_length=255)),
                ('security_clearance_level', models.CharField(blank=True, max_length=255, null=True)),
                ('security_clearance_expiry_date', models.DateField(blank=True, null=True)),
                ('security_clearance_verified', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A')], max_length=5)),
                ('security_file_number', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('candidate_reference_verification', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A')], max_length=5)),
                ('education_verification', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A')], max_length=5)),
                ('candidate_employment', models.CharField(choices=[('independent_contractor', 'Independent Contractor'), ('term_employee', 'Term Employee'), ('employee', 'Employee')], max_length=25)),
                ('candidate_meets_the_mandatory', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A')], max_length=5)),
                ('candidate_rated_requirement', models.IntegerField()),
                ('candidate_language_requirement', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'proposal',
                'verbose_name_plural': 'proposals',
                'db_table': 'proposal',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'recruiter',
                'verbose_name_plural': 'recruiters',
                'db_table': 'recruiter',
            },
        ),
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=75)),
                ('project_description', models.TextField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('security_requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('language_requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('potential_resources', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('technical_evaluation_for_resume', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('financial', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('security', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('education', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('corporate_references', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('candidate_references', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('miscellaneous', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('reviewed', 'Reviewed'), ('ready_to_submit', 'Ready To Submit'), ('submitted', 'Submitted'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('openings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mainapp.opening')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_opening', to='mainapp.proposal')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_opening', to='mainapp.recruiter')),
            ],
            options={
                'verbose_name': 'project_information',
                'verbose_name_plural': 'project_informations',
                'db_table': 'project_information',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_address', models.CharField(blank=True, max_length=255, null=True)),
                ('project_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='mainapp.projectinformation')),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'db_table': 'partner',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_project_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='mainapp.projectinformation')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'db_table': 'job',
            },
        ),
    ]
