# Generated by Django 5.0.6 on 2024-05-20 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_projectfiles_project_info_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfoupdate',
            name='project_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_update_info', to='mainapp.projectinformation'),
        ),
    ]
